### ISSUE TITLE
Bootlint validation

### ISSUE THREAD

**Issue by DfnsPix** [blazeworx/flagstrap#1]
Great plugin, works nicely.

Just one little issue Bootlint validation issue a warning because the button doesn't have a type defined.

Adding attr("type","button") solve the issue.

f=a("<button/>").attr("type","button").attr("data-toggle","dropdown")

**Comment by blazeworx** [comment]
Thank you! 

I will add this in very soon. I am planning on releasing and tagging a 1.0 version in the coming days.

**Comment by blazeworx** [comment]
type attribute has now been added.
