### ISSUE TITLE
Question: Linking to countries URL

### ISSUE THREAD

**Issue by freshy84** [blazeworx/flagstrap#6]
Hi man,

Love you script. Just had a super noob question. How do I actually link the countries to a URL? Example Australia: example.com.au | US: example.com | UK: example.co.uk

Cheers,

Alex

**Comment by sixlive** [comment]
Once #10 gets merged you could do something like this.

```javascript
$('#example').flagStrap({
    onSelect: function(value) {
      var urls = {
        AU: 'http://google.com.au',
        US: 'http://google.com',
        GB: 'http://google.co.uk'
      };

      if (urls[value] !== undefined) {
        window.location.href = urls[value];
      }
    }
});
```

**Comment by freshy84** [comment]
Cheers

**Comment by blazeworx** [comment]
Added by Merge #10

**Comment by marcodiversi** [comment]
hi , using your code it works for all the countries, except the first country in the list does't select ! there's no errors thought !

**Comment by sixlive** [comment]
@marcodiversi Can you get me a codepen of your code so I can take a look at whats going on?

**Comment by marcodiversi** [comment]
hi, have you ever tested it on mobile and on safari ?

it works properly to me only on IE, and on chrome the first country doesn't
pick, and on mobile doesn't pick any country ! where i can send you the
codepen or the website i am trying to make ? thanks my email
marcodiversi@gmail.com



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=marcodiversi@gmail.com&idSignature=22>


*
<https://mailtrack.io/trace/link/9a00520c9d0d4b547765aa87d4f3c74f283447e0?url=http%3A%2F%2F%2F&signature=76084ff4fae74a39>*
*MARCO DIVERSI*
_______________________

[image: mobile] <+32486759717>  [image: LinkedIn]
<https://mailtrack.io/trace/link/14d28c9e8521fdcc322a3142da649b837dc27cf4?url=https%3A%2F%2Flinkedin.com%2Fin%2Fmarcodiversi%2Fen&signature=5cfae6fe86222dc9>
  [image: messenger]
<https://mailtrack.io/trace/link/2a18a4b777189f361beaa844d3139fd5f2a9ba5a?url=https%3A%2F%2Fwww.m.me%2Fmarcodiversi&signature=08fb0f58b3a2d178>
  [image: website]
<https://mailtrack.io/trace/link/061fbb840f64d7853d9c2a530e998c117b32de89?url=http%3A%2F%2Fwww.marcodiversi.com%2F&signature=980aaad94fe61650>

[image: gmail] <marcodiversi@gmail.com>  [image: GitHub]
<https://mailtrack.io/trace/link/c8a099ce934389b73fef2f19b7d465d8c759c1fb?url=https%3A%2F%2Fgithub.com%2Fmarcodiversi&signature=e9c7084d3c54c00f>
  [image: Skype]
<https://mailtrack.io/trace/link/133cc5ded0a6a70ef29828043e1624008b5c1cc2?url=https%3A%2F%2Fweb.skype.com%2Fen%2F&signature=4a8878a5300dc11b>
  [image: PayPal]
<https://mailtrack.io/trace/link/2cf20a836ade86e381d3ebddf9415eb65df1758b?url=https%3A%2F%2Fwww.paypal.me%2Fmarcodiversi&signature=0f82692588ed30f2>

**Comment by sixlive** [comment]
You can just post it here.

**Comment by marcodiversi** [comment]
it's not a cool website to post here but ok, ill delete the comment after the bug is fixed, 

the website is  leadingdate.com  

- first country doesn't work on chrome no matter which one it is .
- country picker doesn't work on mobile and safari 
- everything looks fine on IE i guess ! 

thanks

**Comment by marcodiversi** [comment]
does it actually work on mobile and or safari ? so far it works correctly only on IE for me !

**Comment by przemek286** [comment]
> 

This doesnt work out. Can you help how to add links to submenu items?
