### ISSUE TITLE
Any possible way for me to get the value attribute with your flagstrap...?

### ISSUE THREAD

**Issue by naktieuthu** [blazeworx/flagstrap#7]
I want to get the value from select box. By value here, I mean the ISO alpha2 for countries, for example:

'us': united states
'af': afghanistan
'cn': china

etc...

So, I want to get those us, af, cn .....value. How can I do that ..?

**Comment by nonameolsson** [comment]
I'm also interested in this.

**Comment by sixlive** [comment]
@naktieuthu @nonameolsson What if I added a callback to the options object that would essentially wrap a change event.

```javascript
$('.flagstrap').flagStrap({
  onSelect: function(value, element) {
    // do stuff
  }
});
```

**Comment by nonameolsson** [comment]
@sixlive Yes! :)

**Comment by sixlive** [comment]
@nonameolsson awesome, I'll get a PR together this weekend.

**Comment by blazeworx** [comment]
Added by Merge #10
